# Error Handling - try and except

# try-except block for exception handling


try:
    i = 0
    j = 10 / i
    
except:
    print("Exception Caught!")
    j = 0
print(j)